fed = ["yummy food c:", "thank you {username}!", "you're the best {username} :3"]
disown = ["i'm gonna miss you :((", ":c"]
snowPlay = ["look at my snowman!", "hehe"]
noSnow = ["can we go back insideee :(", ">:(", "i'm colddd"]